name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Run Linter and Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint

    - name: Run Pylint
      run: |
        pylint bot.py  # Add more files as needed

    - name: Run Unit Tests
      run: |
        python -m unittest discover -s tests
      continue-on-error: true  # Optional: allow tests to fail without failing the pipeline
